/**
 * UAE-focused make/model dataset.
 *
 * Bundled (not fetched) — small enough to inline, no network, instant
 * filter when the make changes. Add entries here over time as feedback
 * surfaces missing options.
 *
 * "Other" is a built-in escape hatch handled by the picker component,
 * not encoded in the data itself.
 */

export const MAKES = [
  'Toyota',
  'Nissan',
  'Lexus',
  'Mercedes-Benz',
  'BMW',
  'Audi',
  'Honda',
  'Hyundai',
  'Kia',
  'Ford',
  'GMC',
  'Chevrolet',
  'Land Rover',
  'Range Rover',
  'Jeep',
  'Mitsubishi',
  'Mazda',
  'Volkswagen',
  'Porsche',
  'Tesla',
  'Suzuki',
  'Renault',
  'Peugeot',
  'Dodge',
  'RAM',
  'Cadillac',
  'Infiniti',
  'MG',
  'Volvo',
  'Mini',
  'Bentley',
  'Rolls-Royce',
  'Ferrari',
  'Lamborghini',
  'Maserati',
] as const

export type Make = (typeof MAKES)[number]

export const MODELS_BY_MAKE: Record<string, readonly string[]> = {
  Toyota: [
    'Land Cruiser',
    'Land Cruiser Prado',
    'Corolla',
    'Camry',
    'Yaris',
    'RAV4',
    'Hilux',
    'Fortuner',
    'Avanza',
    'Highlander',
    'FJ Cruiser',
    'Innova',
    'Rush',
    'Hiace',
    'Coaster',
    'GR Supra',
    'GR Yaris',
  ],
  Nissan: [
    'Patrol',
    'Sunny',
    'Altima',
    'Maxima',
    'X-Trail',
    'Kicks',
    'Pathfinder',
    'Sentra',
    'Versa',
    'Murano',
    'Armada',
    'Navara',
    'Urvan',
    '370Z',
    'GT-R',
  ],
  Lexus: ['LX', 'GX', 'RX', 'ES', 'IS', 'LS', 'NX', 'UX', 'LC', 'LM', 'RZ'],
  'Mercedes-Benz': [
    'A-Class',
    'C-Class',
    'E-Class',
    'S-Class',
    'G-Class',
    'GLA',
    'GLB',
    'GLC',
    'GLE',
    'GLS',
    'CLA',
    'CLS',
    'EQE',
    'EQS',
    'AMG GT',
    'V-Class',
    'Sprinter',
  ],
  BMW: [
    '1 Series',
    '2 Series',
    '3 Series',
    '4 Series',
    '5 Series',
    '6 Series',
    '7 Series',
    '8 Series',
    'X1',
    'X2',
    'X3',
    'X4',
    'X5',
    'X6',
    'X7',
    'M2',
    'M3',
    'M4',
    'M5',
    'M8',
    'i3',
    'i4',
    'i5',
    'i7',
    'iX',
    'Z4',
  ],
  Audi: [
    'A1',
    'A3',
    'A4',
    'A5',
    'A6',
    'A7',
    'A8',
    'Q2',
    'Q3',
    'Q4 e-tron',
    'Q5',
    'Q7',
    'Q8',
    'e-tron GT',
    'RS3',
    'RS6',
    'RS7',
    'R8',
    'TT',
  ],
  Honda: [
    'Civic',
    'Accord',
    'CR-V',
    'HR-V',
    'Pilot',
    'Odyssey',
    'Insight',
    'City',
    'Jazz',
    'Type R',
  ],
  Hyundai: [
    'Accent',
    'Elantra',
    'Sonata',
    'Tucson',
    'Santa Fe',
    'Kona',
    'Palisade',
    'Creta',
    'i10',
    'i20',
    'Venue',
    'Staria',
    'Ioniq 5',
    'Ioniq 6',
  ],
  Kia: [
    'Pegas',
    'Cerato',
    'Optima',
    'K5',
    'Sportage',
    'Sorento',
    'Carnival',
    'Picanto',
    'Seltos',
    'Rio',
    'Stinger',
    'EV6',
    'EV9',
  ],
  Ford: [
    'Mustang',
    'F-150',
    'Explorer',
    'Edge',
    'Escape',
    'Bronco',
    'Expedition',
    'Taurus',
    'Focus',
    'Fiesta',
    'Ranger',
    'Raptor',
    'Mustang Mach-E',
  ],
  GMC: ['Yukon', 'Yukon XL', 'Sierra', 'Acadia', 'Terrain', 'Canyon', 'Hummer EV'],
  Chevrolet: [
    'Tahoe',
    'Suburban',
    'Silverado',
    'Malibu',
    'Cruze',
    'Captiva',
    'Spark',
    'Camaro',
    'Corvette',
    'Traverse',
    'Trailblazer',
  ],
  'Land Rover': ['Defender', 'Discovery', 'Discovery Sport', 'Freelander'],
  'Range Rover': [
    'Range Rover',
    'Range Rover Sport',
    'Range Rover Velar',
    'Range Rover Evoque',
  ],
  Jeep: [
    'Wrangler',
    'Grand Cherokee',
    'Compass',
    'Cherokee',
    'Gladiator',
    'Renegade',
    'Wagoneer',
    'Grand Wagoneer',
  ],
  Mitsubishi: [
    'Pajero',
    'Pajero Sport',
    'Outlander',
    'Lancer',
    'ASX',
    'Eclipse Cross',
    'L200',
    'Triton',
    'Attrage',
  ],
  Mazda: [
    'Mazda2',
    'Mazda3',
    'Mazda6',
    'CX-3',
    'CX-5',
    'CX-9',
    'CX-30',
    'CX-50',
    'CX-60',
    'CX-90',
    'MX-5',
  ],
  Volkswagen: [
    'Golf',
    'Passat',
    'Jetta',
    'Tiguan',
    'Touareg',
    'Polo',
    'T-Roc',
    'Teramont',
    'ID.4',
    'ID.6',
    'Arteon',
  ],
  Porsche: [
    '911',
    '718 Cayman',
    '718 Boxster',
    'Cayenne',
    'Macan',
    'Panamera',
    'Taycan',
  ],
  Tesla: ['Model 3', 'Model S', 'Model X', 'Model Y', 'Cybertruck'],
  Suzuki: ['Swift', 'Baleno', 'Vitara', 'Jimny', 'Ciaz', 'Dzire', 'S-Cross'],
  Renault: ['Duster', 'Koleos', 'Megane', 'Captur', 'Symbol', 'Talisman'],
  Peugeot: ['208', '308', '508', '2008', '3008', '5008', 'Partner', 'Rifter'],
  Dodge: ['Challenger', 'Charger', 'Durango', 'Journey', 'Ram'],
  RAM: ['1500', '2500', '3500', 'TRX'],
  Cadillac: ['Escalade', 'CT4', 'CT5', 'CT6', 'XT4', 'XT5', 'XT6', 'Lyriq'],
  Infiniti: ['Q50', 'Q60', 'Q70', 'QX50', 'QX55', 'QX60', 'QX70', 'QX80'],
  MG: ['ZS', 'HS', 'RX5', 'RX8', 'GT', 'Marvel R', 'MG5', 'MG6', 'Cyberster'],
  Volvo: ['XC40', 'XC60', 'XC90', 'S60', 'S90', 'V40', 'V60', 'V90', 'EX30', 'EX90'],
  Mini: ['Cooper', 'Countryman', 'Clubman', 'Cooper SE'],
  Bentley: ['Continental GT', 'Flying Spur', 'Bentayga', 'Mulsanne'],
  'Rolls-Royce': ['Phantom', 'Ghost', 'Wraith', 'Dawn', 'Cullinan', 'Spectre'],
  Ferrari: [
    'F8',
    'Roma',
    'Portofino',
    'SF90',
    '488',
    '296',
    'Purosangue',
    '812',
  ],
  Lamborghini: ['Huracan', 'Urus', 'Aventador', 'Revuelto'],
  Maserati: ['Ghibli', 'Quattroporte', 'Levante', 'GranTurismo', 'MC20', 'Grecale'],
}

export const COMMON_COLORS = [
  'White',
  'Black',
  'Silver',
  'Grey',
  'Beige',
  'Brown',
  'Red',
  'Blue',
  'Green',
  'Gold',
  'Yellow',
  'Orange',
  'Other',
] as const

const CURRENT_YEAR = new Date().getFullYear()
export const YEAR_OPTIONS: readonly string[] = Array.from(
  { length: CURRENT_YEAR + 1 - 1990 + 1 },
  (_, i) => String(CURRENT_YEAR + 1 - i),
)
